name: pudl
channels:
  - conda-forge
  - defaults
  - intake
dependencies:
  - pip~=21.2
  - python>=3.8,<3.10
  - python-snappy~=0.6.0  # Install snappy-dev library without using apt
  - catalystcoop.pudl~=0.4.0

  # Jupyter + Dask for interactive computing
  - dask~=2021.8
  - dask-labextension~=5.1
  - jupyterlab>=3.1,<3.1.5
  - jupyter-offlinenotebook~=0.2
  - jupyter-resource-usage~=0.5
  - nbclassic>=0.2.8
  - nbgitpuller~=0.9
  - python-graphviz
  - seaborn~=0.11

