name: pudl
channels:
  - conda-forge
  - defaults
  - intake
dependencies:
  - pip~=21.2
  - python>=3.8,<3.10
  - geopandas~=0.9.0  # Ensures access to compatible GEOS binaries
  - pygeos~=0.9.0  # Ensures access to compatible GEOS binaries
  - python-snappy~=0.6.0  # Ensures snappy-dev library is installed w/o apt

  # user environment
  - dask~=2021.8
  - dask-labextension~=5.1
  - jupyterlab~=3.1
  - jupyter-resource-usage~=0.5
  - nbgitpuller~=0.9
  - python-graphviz

  - pip:
    - catalystcoop.pudl~=0.4
    - jupyter-offlinenotebook~=0.2
